{% set name = "kerrgeopy" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kerrgeopy-{{ version }}.tar.gz
  sha256: b95b5e31941214115442e21d5e7775fdf5d7285d42ca7687df6f7b0a12977318

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - scipy >=1.8
    - numpy
    - matplotlib-base >=3.7
    - tqdm
    - ffmpeg

test:
  imports:
    - kerrgeopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BlackHolePerturbationToolkit/KerrGeoPy
  summary: Library for computing stable and plunging geodesics in Kerr spacetime
  license: GPL-3.0
  license_file: LICENSE
  doc_url: https://kerrgeopy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - syp2001
